# Generated by Django 5.2 on 2025-05-27 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='Teppo', max_length=50)),
                ('lastname', models.CharField(default='Testaaja', max_length=50)),
                ('address', models.CharField(default='firma', max_length=100)),
                ('phone', models.CharField(default='firma', max_length=20)),
                ('email', models.CharField(default='firma', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storename', models.CharField(default='firma', max_length=50)),
                ('contactname', models.CharField(default='firma', max_length=50)),
                ('address', models.CharField(default='firma', max_length=100)),
                ('phone', models.CharField(default='firma', max_length=20)),
                ('email', models.CharField(default='firma', max_length=50)),
                ('country', models.CharField(default='firma', max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
