# Generated by Django 5.2 on 2025-05-27 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employees_stores'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
        migrations.RenameModel(
            old_name='Stores',
            new_name='Store',
        ),
    ]
