# Generated by Django 5.2 on 2025-05-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_employees_employee_rename_stores_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='product',
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(default='katu', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(default='sposti', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='123', max_length=20),
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(default='katukatu', max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='contactname',
            field=models.CharField(default='Heikki', max_length=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='country',
            field=models.CharField(default='Finland', max_length=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='email',
            field=models.CharField(default='sahkoposti', max_length=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=models.CharField(default='1234', max_length=20),
        ),
        migrations.AlterField(
            model_name='store',
            name='storename',
            field=models.CharField(default='Kauppa', max_length=50),
        ),
    ]
