# Generated by Django 5.2 on 2025-05-28 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ForeignKey(default='kauppa', on_delete=django.db.models.deletion.CASCADE, to='app.store'),
        ),
    ]
