# Generated by Django 5.2 on 2025-06-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_employee_store_alter_product_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='store',
        ),
        migrations.AlterField(
            model_name='store',
            name='storename',
            field=models.CharField(max_length=50),
        ),
    ]
